services:
  club-web:
    container_name: club-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://club.api.nikcnn.xyz}
    ports:
      - "8080:80"
    restart: unless-stopped
